### PR TITLE
Added name to team members in env file

### PR DESCRIPTION
**Pull request by aslamm29**

### CODE REVIEW

**Review by gonzalj3 — COMMENTED** [review]
Hey Aslam I cant approve because I dont see your name name added to the variable TEAM_MEMBERS in the .env file under server. Also I only see changes to the package-lock.json file which may be o.k. but I dont know if these were accidental or not.

**Comment by minhhvu** [comment]
The task requires you to add the name on file /server/env. What did you made change on package.json?

**Comment by aslamm29** [comment]
My previous commit did not go through, changes have been made

**Comment by gonzalj3** [comment]
In Aslam first commit under the client and server directory their are package-lock.json files that have been modified. The image below shows what I see that the files have an additional field ,usually , "optional" assigned to true. A second thing before approving is that pull request is now in conflict since I have updated the dev version of .env with my name. I asked Aecio about this over the weekend and he said that the person who is asking for pull request will have to resolve conflicts; which I think in this case just means that .env file needs to also have my name assigned to TEAM_MEMBERS. 
Screen Shot 2020-03-30 at 9 05 52 AM

**Pull request merged**
